### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by tashian** [SioKCronin/PSO-baselines#4]
- [ ] Dockerize SwarmOpt
- [ ] Focus project on MOPSO, with variants, for industrial applications of CNN tuning

**Comment by SioKCronin** [comment]
Thanks Carl! I changed the name of this issue to "Release v0.1", and fleshed out the list a bit, so this can be a bit of a roadmap.

**Comment by SioKCronin** [comment]
Closing to make space for fresh direction.
