### ISSUE TITLE
Fix Velocity Update Method

### ISSUE THREAD

**Issue by danielkelshaw** [SioKCronin/PSO-baselines#9]
### **Potential Bug in Velocity Update Method:**
https://github.com/SioKCronin/swarmopt/blob/f4d53074d3ae8c2151d626406ba0da095b30cea9/swarmopt/swarm.py#L207

Should the velocity update not be:
`self.pos += self.velocity`

Apologies if this is incorrect, just something I noticed as I was browsing the code.

**Comment by SioKCronin** [comment]
@danielkelshaw I am revitalizing this project and we addressed this. Thanks for flagging the issue! Please let us know if you have anything on your wish list for this project.
